### ISSUE TITLE
[Insight] Text files should end with a newline character - in LICENSE, line 21

### ISSUE THREAD

**Issue by dkreuer** [MetaSyntactical/google-directions-client#2]
**[in LICENSE, line 21](https://github.com/MetaSyntactical/google-directions-client/blob/bfab5e404543d11319f9d2ba59ba5b86db288779/LICENSE#L21)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/dfe46f16-3d58-4c1b-8cd6-e8f0c8e65d9a/analyses/1)_

**Comment by dweichert** [comment]
Missed that one.
